"""initial schema — all platform tables

Revision ID: d07bfc775dfa
Revises: 
Create Date: 2026-07-15 07:39:25.081547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd07bfc775dfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_models',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenants_using', sa.Integer(), nullable=False),
    sa.Column('cost_per_1k', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_p50', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'purpose', name='uq_model_name_purpose')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('target_label', sa.String(length=300), nullable=True),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_tenant_time', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('guardrails',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enforcement', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('triggers_30d', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('health_metrics',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('spark', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('integrations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bot_limit', sa.Integer(), nullable=False),
    sa.Column('minutes_included', sa.Integer(), nullable=False),
    sa.Column('seats_included', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('platform_templates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_platform_templates_kind', 'platform_templates', ['kind'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sip_trunks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('capacity_lines', sa.Integer(), nullable=False),
    sa.Column('active_calls', sa.Integer(), nullable=False),
    sa.Column('failure_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supported_languages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('accent', sa.String(length=100), nullable=True),
    sa.Column('styles', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=False),
    sa.Column('sample_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_defs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('example', sa.String(length=300), nullable=True),
    sa.Column('pii', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_entity_tenant_name')
    )
    op.create_index(op.f('ix_entity_defs_tenant_id'), 'entity_defs', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index('ix_invoices_tenant_issued', 'invoices', ['tenant_id', 'issued_at'], unique=False)
    op.create_table('platform_alerts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_status_time', 'platform_alerts', ['status', 'occurred_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('permission_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('bot_limit', sa.Integer(), nullable=False),
    sa.Column('minutes_included', sa.Integer(), nullable=False),
    sa.Column('renews_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mrr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_index('ix_subscriptions_tenant_status', 'subscriptions', ['tenant_id', 'status'], unique=False)
    op.create_table('tenant_integrations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('integration_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'integration_id', name='uq_tenant_integration')
    )
    op.create_index(op.f('ix_tenant_integrations_tenant_id'), 'tenant_integrations', ['tenant_id'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_languages', sa.JSON(), nullable=True),
    sa.Column('branding', sa.JSON(), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('holidays', sa.JSON(), nullable=True),
    sa.Column('notifications', sa.JSON(), nullable=True),
    sa.Column('security', sa.JSON(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('voice_bots',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('use_case', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('live_version', sa.String(length=20), nullable=True),
    sa.Column('owner_user_id', sa.String(length=40), nullable=True),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('containment', sa.Float(), nullable=False),
    sa.Column('avg_cost_per_call', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('csat', sa.Float(), nullable=False),
    sa.Column('voice_id', sa.String(length=40), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_bots_tenant_id'), 'voice_bots', ['tenant_id'], unique=False)
    op.create_index('ix_voice_bots_tenant_status', 'voice_bots', ['tenant_id', 'status'], unique=False)
    op.create_table('api_connections',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('secret_ref', sa.String(length=300), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('response_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_latency_ms', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_connections_bot', 'api_connections', ['bot_id'], unique=False)
    op.create_index(op.f('ix_api_connections_tenant_id'), 'api_connections', ['tenant_id'], unique=False)
    op.create_table('bot_languages',
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('language_code', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['supported_languages.code'], ),
    sa.PrimaryKeyConstraint('bot_id', 'language_code')
    )
    op.create_table('channel_configs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('workflow_name', sa.String(length=200), nullable=True),
    sa.Column('last_test', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'type', name='uq_channel_bot_type')
    )
    op.create_index(op.f('ix_channel_configs_bot_id'), 'channel_configs', ['bot_id'], unique=False)
    op.create_index(op.f('ix_channel_configs_tenant_id'), 'channel_configs', ['tenant_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('caller_masked', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('intents', sa.JSON(), nullable=True),
    sa.Column('contained', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.String(length=300), nullable=True),
    sa.Column('csat', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('language', sa.String(length=15), nullable=True),
    sa.Column('qa_score', sa.Integer(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_bot_started', 'conversation_sessions', ['bot_id', 'started_at'], unique=False)
    op.create_index('ix_conversations_tenant_started', 'conversation_sessions', ['tenant_id', 'started_at'], unique=False)
    op.create_table('intents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('samples', sa.JSON(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('avg_confidence_30d', sa.Float(), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('test_pass', sa.Integer(), nullable=False),
    sa.Column('test_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'name', name='uq_intent_bot_name')
    )
    op.create_index('ix_intents_bot', 'intents', ['bot_id'], unique=False)
    op.create_index(op.f('ix_intents_tenant_id'), 'intents', ['tenant_id'], unique=False)
    op.create_table('knowledge_gaps',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('last_asked_at', sa.DateTime(), nullable=True),
    sa.Column('suggested_source', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_gaps_tenant_id'), 'knowledge_gaps', ['tenant_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=True),
    sa.Column('bot_id', sa.String(length=40), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chunks', sa.Integer(), nullable=False),
    sa.Column('size_kb', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('usage_30d', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_bot_id'), 'knowledge_sources', ['bot_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_tenant_id'), 'knowledge_sources', ['tenant_id'], unique=False)
    op.create_index('ix_knowledge_tenant_scope', 'knowledge_sources', ['tenant_id', 'scope'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('tenant_id', sa.String(length=40), nullable=True),
    sa.Column('bot_id', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_phone_numbers_tenant', 'phone_numbers', ['tenant_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('active_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompts_bot', 'prompts', ['bot_id'], unique=False)
    op.create_index(op.f('ix_prompts_tenant_id'), 'prompts', ['tenant_id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=150), nullable=True),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_releases_bot', 'releases', ['bot_id'], unique=False)
    op.create_index(op.f('ix_releases_tenant_id'), 'releases', ['tenant_id'], unique=False)
    op.create_table('test_scenarios',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('suite', sa.String(length=100), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_scenarios_bot', 'test_scenarios', ['bot_id'], unique=False)
    op.create_index(op.f('ix_test_scenarios_tenant_id'), 'test_scenarios', ['tenant_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('contained_calls', sa.Integer(), nullable=False),
    sa.Column('escalations', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('csat_avg', sa.Float(), nullable=True),
    sa.Column('cost_llm', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cost_tts', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cost_stt', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cost_telephony', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'bot_id', 'date', name='uq_usage_tenant_bot_date')
    )
    op.create_index('ix_usage_date', 'usage_records', ['date'], unique=False)
    op.create_index('ix_usage_tenant_date', 'usage_records', ['tenant_id', 'date'], unique=False)
    op.create_table('voice_bot_readiness',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('item_key', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('studio_tab', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'item_key', name='uq_readiness_bot_item')
    )
    op.create_index(op.f('ix_voice_bot_readiness_bot_id'), 'voice_bot_readiness', ['bot_id'], unique=False)
    op.create_table('voice_bot_settings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('voice_id', sa.String(length=40), nullable=True),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pause_ms', sa.Integer(), nullable=False),
    sa.Column('empathy', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('language_voice_map', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id')
    )
    op.create_index(op.f('ix_voice_bot_settings_tenant_id'), 'voice_bot_settings', ['tenant_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('bot_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['voice_bots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_bot', 'workflows', ['bot_id'], unique=False)
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('prompt_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('edited_by', sa.String(length=150), nullable=True),
    sa.Column('edited_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'version', name='uq_prompt_version')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_id'), 'prompt_versions', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_versions_prompt_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_index('ix_workflows_bot', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_voice_bot_settings_tenant_id'), table_name='voice_bot_settings')
    op.drop_table('voice_bot_settings')
    op.drop_index(op.f('ix_voice_bot_readiness_bot_id'), table_name='voice_bot_readiness')
    op.drop_table('voice_bot_readiness')
    op.drop_index('ix_usage_tenant_date', table_name='usage_records')
    op.drop_index('ix_usage_date', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_test_scenarios_tenant_id'), table_name='test_scenarios')
    op.drop_index('ix_test_scenarios_bot', table_name='test_scenarios')
    op.drop_table('test_scenarios')
    op.drop_index(op.f('ix_releases_tenant_id'), table_name='releases')
    op.drop_index('ix_releases_bot', table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_prompts_tenant_id'), table_name='prompts')
    op.drop_index('ix_prompts_bot', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('ix_phone_numbers_tenant', table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index('ix_knowledge_tenant_scope', table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_tenant_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_bot_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_knowledge_gaps_tenant_id'), table_name='knowledge_gaps')
    op.drop_table('knowledge_gaps')
    op.drop_index(op.f('ix_intents_tenant_id'), table_name='intents')
    op.drop_index('ix_intents_bot', table_name='intents')
    op.drop_table('intents')
    op.drop_index('ix_conversations_tenant_started', table_name='conversation_sessions')
    op.drop_index('ix_conversations_bot_started', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_channel_configs_tenant_id'), table_name='channel_configs')
    op.drop_index(op.f('ix_channel_configs_bot_id'), table_name='channel_configs')
    op.drop_table('channel_configs')
    op.drop_table('bot_languages')
    op.drop_index(op.f('ix_api_connections_tenant_id'), table_name='api_connections')
    op.drop_index('ix_api_connections_bot', table_name='api_connections')
    op.drop_table('api_connections')
    op.drop_index('ix_voice_bots_tenant_status', table_name='voice_bots')
    op.drop_index(op.f('ix_voice_bots_tenant_id'), table_name='voice_bots')
    op.drop_table('voice_bots')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_settings')
    op.drop_index(op.f('ix_tenant_integrations_tenant_id'), table_name='tenant_integrations')
    op.drop_table('tenant_integrations')
    op.drop_index('ix_subscriptions_tenant_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('role_permissions')
    op.drop_index('ix_alerts_status_time', table_name='platform_alerts')
    op.drop_table('platform_alerts')
    op.drop_index('ix_invoices_tenant_issued', table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_entity_defs_tenant_id'), table_name='entity_defs')
    op.drop_table('entity_defs')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('system_settings')
    op.drop_table('supported_languages')
    op.drop_table('sip_trunks')
    op.drop_table('roles')
    op.drop_index('ix_platform_templates_kind', table_name='platform_templates')
    op.drop_table('platform_templates')
    op.drop_table('plans')
    op.drop_table('permissions')
    op.drop_table('integrations')
    op.drop_table('health_metrics')
    op.drop_table('guardrails')
    op.drop_index('ix_audit_tenant_time', table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('approved_models')
    # ### end Alembic commands ###
